# ESTE ARQUIVO FUNCIONOU ATÉ MESMO ANTES DE DAR ERRO NA MAQUINA DO WESLEY
# O que aconteceu, é que o php fpm, buscou na pasta var/www/html, entao ele mesmo
# nao esta encontrando o arquivo
FROM nginx:1.15.0-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

RUN mkdir /var/www/public -p && touch /var/www/public/index.php